/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      systemHealth: TaskSystemHealth;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'owner' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  kind: 'region' | 'project' | 'complex' | 'og' | 'ui';
  decorative: boolean;
  /**
   * Use an empty string only when decorative is enabled.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Legacy media registry id for seeded assets, or a human-readable source label for new uploads.
   */
  sourceLabel?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  path: string;
  status: 'draft' | 'published' | 'archived';
  summary?: string | null;
  seo: {
    title?: string | null;
    description?: string | null;
    canonicalOverride?: string | null;
    ogImagePath?: string | null;
    robots: 'index-follow' | 'noindex-follow';
    priority: 'P1' | 'P2' | 'P3';
  };
  blocks: (
    | {
        eyebrow?: string | null;
        title: string;
        lead: string;
        primaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        proof?: string | null;
        imagePath?: string | null;
        imageAlt?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow?: string | null;
        title: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'lead';
      }
    | {
        title: string;
        items: {
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'thesis';
      }
    | {
        title: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'risk-block';
      }
    | {
        eyebrow?: string | null;
        title: string;
        lead?: string | null;
        steps: {
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'numbered-steps';
      }
    | {
        title: string;
        proof: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'proof-block';
      }
    | {
        title: string;
        rows: {
          scenario: string;
          assumption: string;
          investorQuestion: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'scenario-table';
      }
    | {
        title: string;
        lead?: string | null;
        cards: {
          title: string;
          text: string;
          link?: {
            label?: string | null;
            href?: string | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cards-grid';
      }
    | {
        title: string;
        lead?: string | null;
        items: {
          title: string;
          href: string;
          location: string;
          status: string;
          thesis: string;
          risk: string;
          imagePath?: string | null;
          imageAlt?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'object-cards';
      }
    | {
        title: string;
        text: string;
        primaryCta: {
          label: string;
          href: string;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'rich-text';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  source: string;
  destination: string;
  permanent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'systemHealth';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'systemHealth') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  kind?: T;
  decorative?: T;
  alt?: T;
  caption?: T;
  sourceLabel?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  path?: T;
  status?: T;
  summary?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImagePath?: T;
        robots?: T;
        priority?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              proof?: T;
              imagePath?: T;
              imageAlt?: T;
              id?: T;
              blockName?: T;
            };
        lead?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        thesis?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'risk-block'?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        'numbered-steps'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'proof-block'?:
          | T
          | {
              title?: T;
              proof?: T;
              id?: T;
              blockName?: T;
            };
        'scenario-table'?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    scenario?: T;
                    assumption?: T;
                    investorQuestion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cards-grid'?:
          | T
          | {
              title?: T;
              lead?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'object-cards'?:
          | T
          | {
              title?: T;
              lead?: T;
              items?:
                | T
                | {
                    title?: T;
                    href?: T;
                    location?: T;
                    status?: T;
                    thesis?: T;
                    risk?: T;
                    imagePath?: T;
                    imageAlt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  source?: T;
  destination?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  shortName: string;
  tagline?: string | null;
  /**
   * Owner-filled production origin, for example https://example.ru. Empty until domain is approved.
   */
  canonicalDomain?: string | null;
  contacts?: {
    phone?: string | null;
    email?: string | null;
    telegram?: string | null;
    whatsapp?: string | null;
    address?: string | null;
    workingHours?: string | null;
  };
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo: {
    title?: string | null;
    description?: string | null;
    ogImagePath?: string | null;
    robots: 'index-follow' | 'noindex-follow';
  };
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalNotice?: string | null;
  /**
   * Public analytics identifiers only. Secrets and tokens stay in env/secret manager.
   */
  analytics?: {
    yandexMetrikaId?: string | null;
    vkPixelId?: string | null;
    callTrackingId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        nofollow?: boolean | null;
        id?: string | null;
      }[]
    | null;
  headerCta?: {
    label?: string | null;
    href?: string | null;
  };
  footer?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        nofollow?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legal?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        nofollow?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  tagline?: T;
  canonicalDomain?: T;
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        telegram?: T;
        whatsapp?: T;
        address?: T;
        workingHours?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImagePath?: T;
        robots?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalNotice?: T;
  analytics?:
    | T
    | {
        yandexMetrikaId?: T;
        vkPixelId?: T;
        callTrackingId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        nofollow?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        nofollow?: T;
        id?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        nofollow?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSystemHealth".
 */
export interface TaskSystemHealth {
  input?: unknown;
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}