/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    regions: Region;
    redirects: Redirect;
    'feed-sources': FeedSource;
    'import-runs': ImportRun;
    'import-issues': ImportIssue;
    leads: Lead;
    'lead-deliveries': LeadDelivery;
    properties: Property;
    developers: Developer;
    'residential-complexes': ResidentialComplex;
    buildings: Building;
    layouts: Layout;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'feed-sources': FeedSourcesSelect<false> | FeedSourcesSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'import-issues': ImportIssuesSelect<false> | ImportIssuesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-deliveries': LeadDeliveriesSelect<false> | LeadDeliveriesSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    developers: DevelopersSelect<false> | DevelopersSelect<true>;
    'residential-complexes': ResidentialComplexesSelect<false> | ResidentialComplexesSelect<true>;
    buildings: BuildingsSelect<false> | BuildingsSelect<true>;
    layouts: LayoutsSelect<false> | LayoutsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      systemHealth: TaskSystemHealth;
      dispatchDueFeeds: TaskDispatchDueFeeds;
      importFeed: TaskImportFeed;
      deliverLead: TaskDeliverLead;
      jobsJanitor: TaskJobsJanitor;
      recoverLeadDeliveries: TaskRecoverLeadDeliveries;
      catalogLifecycle: TaskCatalogLifecycle;
      leadRetentionCleanup: TaskLeadRetentionCleanup;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'owner' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  kind: 'region' | 'project' | 'complex' | 'og' | 'ui';
  decorative: boolean;
  /**
   * Use an empty string only when decorative is enabled.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Legacy media registry id for seeded assets, or a human-readable source label for new uploads.
   */
  sourceLabel?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  path: string;
  status: 'draft' | 'published' | 'archived';
  summary?: string | null;
  seo: {
    title?: string | null;
    description?: string | null;
    canonicalOverride?: string | null;
    ogImagePath?: string | null;
    robots: 'index-follow' | 'noindex-follow';
    priority: 'P1' | 'P2' | 'P3';
  };
  blocks: (
    | {
        eyebrow?: string | null;
        title: string;
        lead: string;
        primaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        proof?: string | null;
        imagePath?: string | null;
        imageAlt?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow?: string | null;
        title: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'lead';
      }
    | {
        title: string;
        items: {
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'thesis';
      }
    | {
        title: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'risk-block';
      }
    | {
        eyebrow?: string | null;
        title: string;
        lead?: string | null;
        steps: {
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'numbered-steps';
      }
    | {
        title: string;
        proof: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'proof-block';
      }
    | {
        title: string;
        rows: {
          scenario: string;
          assumption: string;
          investorQuestion: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'scenario-table';
      }
    | {
        title: string;
        lead?: string | null;
        cards: {
          title: string;
          text: string;
          link?: {
            label?: string | null;
            href?: string | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cards-grid';
      }
    | {
        title: string;
        lead?: string | null;
        items: {
          title: string;
          href: string;
          location: string;
          status: string;
          thesis: string;
          risk: string;
          imagePath?: string | null;
          imageAlt?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'object-cards';
      }
    | {
        title: string;
        text: string;
        primaryCta: {
          label: string;
          href: string;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'rich-text';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  title: string;
  slug: string;
  kind: 'region' | 'locality' | 'segment';
  parent?: (number | null) | Region;
  order: number;
  lead: string;
  investmentThesis: string;
  riskSummary: string;
  heroMedia: number | Media;
  blocks: (
    | {
        eyebrow?: string | null;
        title: string;
        lead: string;
        primaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        proof?: string | null;
        imagePath?: string | null;
        imageAlt?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow?: string | null;
        title: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'lead';
      }
    | {
        title: string;
        items: {
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'thesis';
      }
    | {
        title: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'risk-block';
      }
    | {
        eyebrow?: string | null;
        title: string;
        lead?: string | null;
        steps: {
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'numbered-steps';
      }
    | {
        title: string;
        proof: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'proof-block';
      }
    | {
        title: string;
        rows: {
          scenario: string;
          assumption: string;
          investorQuestion: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'scenario-table';
      }
    | {
        title: string;
        lead?: string | null;
        cards: {
          title: string;
          text: string;
          link?: {
            label?: string | null;
            href?: string | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cards-grid';
      }
    | {
        title: string;
        lead?: string | null;
        items: {
          title: string;
          href: string;
          location: string;
          status: string;
          thesis: string;
          risk: string;
          imagePath?: string | null;
          imageAlt?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'object-cards';
      }
    | {
        title: string;
        text: string;
        primaryCta: {
          label: string;
          href: string;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'rich-text';
      }
  )[];
  seo: {
    title?: string | null;
    description?: string | null;
    canonicalOverride?: string | null;
    ogImagePath?: string | null;
    robots: 'index-follow' | 'noindex-follow';
    priority: 'P1' | 'P2' | 'P3';
  };
  status: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  source: string;
  destination: string;
  permanent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources".
 */
export interface FeedSource {
  id: number;
  code: string;
  parser?: string | null;
  market: 'secondary' | 'newbuild';
  /**
   * Secret Master reference only. Do not store raw feed credentials here.
   */
  feedUrlRef?: string | null;
  enabled: boolean;
  refreshIntervalMinutes: number;
  nextDueAt?: string | null;
  lastAttemptAt?: string | null;
  lastSuccessfulRunAt?: string | null;
  lastFullRunAt?: string | null;
  safetyThresholdPercent: number;
  maxDeactivationsPerRun: number;
  lastOfferCount?: number | null;
  lastEtag?: string | null;
  lastModified?: string | null;
  lastFeedHash?: string | null;
  deactivationApproval?: {
    runId?: string | null;
    approvedBy?: string | null;
    approvedAt?: string | null;
    expiresAt?: string | null;
    consumedAt?: string | null;
    decision?: ('approved' | 'rejected') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  feedSource: number | FeedSource;
  status: 'queued' | 'running' | 'completed' | 'suspicious' | 'failed' | 'skipped' | 'interrupted';
  mode: 'incremental' | 'full';
  jobId?: string | null;
  startedAt?: string | null;
  heartbeatAt?: string | null;
  finishedAt?: string | null;
  feedHash?: string | null;
  etag?: string | null;
  lastModified?: string | null;
  offeredCount?: number | null;
  createdCount: number;
  updatedCount: number;
  skippedCount: number;
  deactivatedCount: number;
  issueCount: number;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-issues".
 */
export interface ImportIssue {
  id: number;
  feedSource: number | FeedSource;
  importRun: number | ImportRun;
  severity: 'info' | 'warning' | 'error' | 'critical';
  code: string;
  externalId?: string | null;
  path?: string | null;
  message: string;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status: 'new' | 'processing' | 'closed' | 'spam';
  retentionStatus: 'active' | 'pii_anonymized';
  name: string;
  phone: string;
  email?: string | null;
  message: string;
  sourcePath: string;
  formId?: string | null;
  consent: {
    accepted: boolean;
    version: string;
    acceptedAt: string;
  };
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  piiAnonymizedAt?: string | null;
  historyPurgeAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner-only manual retry for abandoned rows: POST /api/lead-deliveries/:id/retry. See docs/OPERATIONS.md.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-deliveries".
 */
export interface LeadDelivery {
  id: number;
  lead: number | Lead;
  channelId: string;
  status: 'pending' | 'sending' | 'sent' | 'failed' | 'abandoned';
  attempts: number;
  nextAttemptAt?: string | null;
  idempotencyKey: string;
  externalRef?: string | null;
  lastErrorRedacted?: string | null;
  claimedAt?: string | null;
  heartbeatAt?: string | null;
  manualRetryAudit?:
    | {
        requestedAt: string;
        actorRef: string;
        reasonRedacted?: string | null;
        id?: string | null;
      }[]
    | null;
  attemptLog?:
    | {
        attemptedAt: string;
        outcome: 'pending' | 'sending' | 'sent' | 'failed' | 'abandoned';
        safeCode?: string | null;
        redactedMessage?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  origin: 'feed' | 'manual';
  feedSource?: (number | null) | FeedSource;
  externalId?: string | null;
  importHash?: string | null;
  firstSeenAt?: string | null;
  lastSeenAt?: string | null;
  lastImportRun?: string | null;
  externalComplexId?: string | null;
  externalComplexName?: string | null;
  externalBuildingId?: string | null;
  externalLayoutId?: string | null;
  complex?: (number | null) | ResidentialComplex;
  building?: (number | null) | Building;
  layout?: (number | null) | Layout;
  status: 'active' | 'archived';
  deactivatedAt?: string | null;
  deactivatedByRun?: string | null;
  needsReview: boolean;
  publishedAt?: string | null;
  slug?: string | null;
  market: 'secondary' | 'newbuild';
  category?: ('apartment' | 'house' | 'land' | 'commercial') | null;
  dealType?: ('sale' | 'rent') | null;
  priceMinor?: number | null;
  currency?: string | null;
  pricePerMeterMinor?: number | null;
  rooms?: number | null;
  totalArea?: number | null;
  livingArea?: number | null;
  kitchenArea?: number | null;
  floor?: number | null;
  floors?: number | null;
  region?: (number | null) | Region;
  locality?: string | null;
  district?: string | null;
  street?: string | null;
  house?: string | null;
  publicAddress?: string | null;
  lat?: number | null;
  lng?: number | null;
  title: string;
  description?: string | null;
  images?: (number | Media)[] | null;
  unitNumber?: string | null;
  cadastralNumber?: string | null;
  internalComment?: string | null;
  ownerContact?: string | null;
  verdict?: string | null;
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  budgetNote?: string | null;
  riskSummary?: string | null;
  sources?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes".
 */
export interface ResidentialComplex {
  id: number;
  slug: string;
  title: string;
  developer: number | Developer;
  region: number | Region;
  feedSource?: (number | null) | FeedSource;
  externalComplexId?: string | null;
  address?: {
    locality?: string | null;
    district?: string | null;
    street?: string | null;
    house?: string | null;
    publicAddress?: string | null;
    lat?: number | null;
    lng?: number | null;
  };
  media?: (number | Media)[] | null;
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            lead: string;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            proof?: string | null;
            imagePath?: string | null;
            imageAlt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lead';
          }
        | {
            title: string;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'thesis';
          }
        | {
            title: string;
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'risk-block';
          }
        | {
            eyebrow?: string | null;
            title: string;
            lead?: string | null;
            steps: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'numbered-steps';
          }
        | {
            title: string;
            proof: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'proof-block';
          }
        | {
            title: string;
            rows: {
              scenario: string;
              assumption: string;
              investorQuestion: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'scenario-table';
          }
        | {
            title: string;
            lead?: string | null;
            cards: {
              title: string;
              text: string;
              link?: {
                label?: string | null;
                href?: string | null;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards-grid';
          }
        | {
            title: string;
            lead?: string | null;
            items: {
              title: string;
              href: string;
              location: string;
              status: string;
              thesis: string;
              risk: string;
              imagePath?: string | null;
              imageAlt?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'object-cards';
          }
        | {
            title: string;
            text: string;
            primaryCta: {
              label: string;
              href: string;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
      )[]
    | null;
  seo: {
    title?: string | null;
    description?: string | null;
    canonicalOverride?: string | null;
    ogImagePath?: string | null;
    robots: 'index-follow' | 'noindex-follow';
    priority: 'P1' | 'P2' | 'P3';
  };
  status: 'hidden' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers".
 */
export interface Developer {
  id: number;
  slug: string;
  title: string;
  description?: string | null;
  media?: (number | Media)[] | null;
  seo: {
    title?: string | null;
    description?: string | null;
    canonicalOverride?: string | null;
    ogImagePath?: string | null;
    robots: 'index-follow' | 'noindex-follow';
    priority: 'P1' | 'P2' | 'P3';
  };
  status: 'hidden' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings".
 */
export interface Building {
  id: number;
  complex: number | ResidentialComplex;
  externalBuildingId?: string | null;
  name: string;
  completionDeadline?: string | null;
  status: 'hidden' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layouts".
 */
export interface Layout {
  id: number;
  complex: number | ResidentialComplex;
  building?: (number | null) | Building;
  externalLayoutId: string;
  rooms?: number | null;
  totalArea?: number | null;
  plan?: (number | null) | Media;
  status: 'hidden' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Read-only owner diagnostics for queued jobs. Mutations stay blocked.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'systemHealth'
          | 'dispatchDueFeeds'
          | 'importFeed'
          | 'deliverLead'
          | 'jobsJanitor'
          | 'recoverLeadDeliveries'
          | 'catalogLifecycle'
          | 'leadRetentionCleanup';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'systemHealth'
        | 'dispatchDueFeeds'
        | 'importFeed'
        | 'deliverLead'
        | 'jobsJanitor'
        | 'recoverLeadDeliveries'
        | 'catalogLifecycle'
        | 'leadRetentionCleanup'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'feed-sources';
        value: number | FeedSource;
      } | null)
    | ({
        relationTo: 'developers';
        value: number | Developer;
      } | null)
    | ({
        relationTo: 'residential-complexes';
        value: number | ResidentialComplex;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  kind?: T;
  decorative?: T;
  alt?: T;
  caption?: T;
  sourceLabel?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  path?: T;
  status?: T;
  summary?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImagePath?: T;
        robots?: T;
        priority?: T;
      };
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              proof?: T;
              imagePath?: T;
              imageAlt?: T;
              id?: T;
              blockName?: T;
            };
        lead?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        thesis?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'risk-block'?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        'numbered-steps'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'proof-block'?:
          | T
          | {
              title?: T;
              proof?: T;
              id?: T;
              blockName?: T;
            };
        'scenario-table'?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    scenario?: T;
                    assumption?: T;
                    investorQuestion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cards-grid'?:
          | T
          | {
              title?: T;
              lead?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'object-cards'?:
          | T
          | {
              title?: T;
              lead?: T;
              items?:
                | T
                | {
                    title?: T;
                    href?: T;
                    location?: T;
                    status?: T;
                    thesis?: T;
                    risk?: T;
                    imagePath?: T;
                    imageAlt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  parent?: T;
  order?: T;
  lead?: T;
  investmentThesis?: T;
  riskSummary?: T;
  heroMedia?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              proof?: T;
              imagePath?: T;
              imageAlt?: T;
              id?: T;
              blockName?: T;
            };
        lead?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        thesis?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'risk-block'?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        'numbered-steps'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'proof-block'?:
          | T
          | {
              title?: T;
              proof?: T;
              id?: T;
              blockName?: T;
            };
        'scenario-table'?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    scenario?: T;
                    assumption?: T;
                    investorQuestion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cards-grid'?:
          | T
          | {
              title?: T;
              lead?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'object-cards'?:
          | T
          | {
              title?: T;
              lead?: T;
              items?:
                | T
                | {
                    title?: T;
                    href?: T;
                    location?: T;
                    status?: T;
                    thesis?: T;
                    risk?: T;
                    imagePath?: T;
                    imageAlt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImagePath?: T;
        robots?: T;
        priority?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  source?: T;
  destination?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources_select".
 */
export interface FeedSourcesSelect<T extends boolean = true> {
  code?: T;
  parser?: T;
  market?: T;
  feedUrlRef?: T;
  enabled?: T;
  refreshIntervalMinutes?: T;
  nextDueAt?: T;
  lastAttemptAt?: T;
  lastSuccessfulRunAt?: T;
  lastFullRunAt?: T;
  safetyThresholdPercent?: T;
  maxDeactivationsPerRun?: T;
  lastOfferCount?: T;
  lastEtag?: T;
  lastModified?: T;
  lastFeedHash?: T;
  deactivationApproval?:
    | T
    | {
        runId?: T;
        approvedBy?: T;
        approvedAt?: T;
        expiresAt?: T;
        consumedAt?: T;
        decision?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  feedSource?: T;
  status?: T;
  mode?: T;
  jobId?: T;
  startedAt?: T;
  heartbeatAt?: T;
  finishedAt?: T;
  feedHash?: T;
  etag?: T;
  lastModified?: T;
  offeredCount?: T;
  createdCount?: T;
  updatedCount?: T;
  skippedCount?: T;
  deactivatedCount?: T;
  issueCount?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-issues_select".
 */
export interface ImportIssuesSelect<T extends boolean = true> {
  feedSource?: T;
  importRun?: T;
  severity?: T;
  code?: T;
  externalId?: T;
  path?: T;
  message?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  retentionStatus?: T;
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  sourcePath?: T;
  formId?: T;
  consent?:
    | T
    | {
        accepted?: T;
        version?: T;
        acceptedAt?: T;
      };
  utm?: T;
  metadata?: T;
  piiAnonymizedAt?: T;
  historyPurgeAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-deliveries_select".
 */
export interface LeadDeliveriesSelect<T extends boolean = true> {
  lead?: T;
  channelId?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  idempotencyKey?: T;
  externalRef?: T;
  lastErrorRedacted?: T;
  claimedAt?: T;
  heartbeatAt?: T;
  manualRetryAudit?:
    | T
    | {
        requestedAt?: T;
        actorRef?: T;
        reasonRedacted?: T;
        id?: T;
      };
  attemptLog?:
    | T
    | {
        attemptedAt?: T;
        outcome?: T;
        safeCode?: T;
        redactedMessage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  origin?: T;
  feedSource?: T;
  externalId?: T;
  importHash?: T;
  firstSeenAt?: T;
  lastSeenAt?: T;
  lastImportRun?: T;
  externalComplexId?: T;
  externalComplexName?: T;
  externalBuildingId?: T;
  externalLayoutId?: T;
  complex?: T;
  building?: T;
  layout?: T;
  status?: T;
  deactivatedAt?: T;
  deactivatedByRun?: T;
  needsReview?: T;
  publishedAt?: T;
  slug?: T;
  market?: T;
  category?: T;
  dealType?: T;
  priceMinor?: T;
  currency?: T;
  pricePerMeterMinor?: T;
  rooms?: T;
  totalArea?: T;
  livingArea?: T;
  kitchenArea?: T;
  floor?: T;
  floors?: T;
  region?: T;
  locality?: T;
  district?: T;
  street?: T;
  house?: T;
  publicAddress?: T;
  lat?: T;
  lng?: T;
  title?: T;
  description?: T;
  images?: T;
  unitNumber?: T;
  cadastralNumber?: T;
  internalComment?: T;
  ownerContact?: T;
  verdict?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  budgetNote?: T;
  riskSummary?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers_select".
 */
export interface DevelopersSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  media?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImagePath?: T;
        robots?: T;
        priority?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes_select".
 */
export interface ResidentialComplexesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  developer?: T;
  region?: T;
  feedSource?: T;
  externalComplexId?: T;
  address?:
    | T
    | {
        locality?: T;
        district?: T;
        street?: T;
        house?: T;
        publicAddress?: T;
        lat?: T;
        lng?: T;
      };
  media?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              proof?: T;
              imagePath?: T;
              imageAlt?: T;
              id?: T;
              blockName?: T;
            };
        lead?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        thesis?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'risk-block'?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        'numbered-steps'?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'proof-block'?:
          | T
          | {
              title?: T;
              proof?: T;
              id?: T;
              blockName?: T;
            };
        'scenario-table'?:
          | T
          | {
              title?: T;
              rows?:
                | T
                | {
                    scenario?: T;
                    assumption?: T;
                    investorQuestion?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cards-grid'?:
          | T
          | {
              title?: T;
              lead?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'object-cards'?:
          | T
          | {
              title?: T;
              lead?: T;
              items?:
                | T
                | {
                    title?: T;
                    href?: T;
                    location?: T;
                    status?: T;
                    thesis?: T;
                    risk?: T;
                    imagePath?: T;
                    imageAlt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalOverride?: T;
        ogImagePath?: T;
        robots?: T;
        priority?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings_select".
 */
export interface BuildingsSelect<T extends boolean = true> {
  complex?: T;
  externalBuildingId?: T;
  name?: T;
  completionDeadline?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layouts_select".
 */
export interface LayoutsSelect<T extends boolean = true> {
  complex?: T;
  building?: T;
  externalLayoutId?: T;
  rooms?: T;
  totalArea?: T;
  plan?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  shortName: string;
  tagline?: string | null;
  /**
   * Owner-filled production origin, for example https://example.ru. Empty until domain is approved.
   */
  canonicalDomain?: string | null;
  contacts?: {
    phone?: string | null;
    email?: string | null;
    telegram?: string | null;
    whatsapp?: string | null;
    address?: string | null;
    workingHours?: string | null;
  };
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo: {
    title?: string | null;
    description?: string | null;
    ogImagePath?: string | null;
    robots: 'index-follow' | 'noindex-follow';
  };
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalNotice?: string | null;
  /**
   * Public analytics identifiers only. Secrets and tokens stay in env/secret manager.
   */
  analytics?: {
    yandexMetrikaId?: string | null;
    vkPixelId?: string | null;
    callTrackingId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        nofollow?: boolean | null;
        id?: string | null;
      }[]
    | null;
  headerCta?: {
    label?: string | null;
    href?: string | null;
  };
  footer?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        nofollow?: boolean | null;
        id?: string | null;
      }[]
    | null;
  legal?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        nofollow?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  tagline?: T;
  canonicalDomain?: T;
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        telegram?: T;
        whatsapp?: T;
        address?: T;
        workingHours?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImagePath?: T;
        robots?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalNotice?: T;
  analytics?:
    | T
    | {
        yandexMetrikaId?: T;
        vkPixelId?: T;
        callTrackingId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        nofollow?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        nofollow?: T;
        id?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        nofollow?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSystemHealth".
 */
export interface TaskSystemHealth {
  input?: unknown;
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDispatchDueFeeds".
 */
export interface TaskDispatchDueFeeds {
  input?: unknown;
  output: {
    claimed: number;
    queued: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskImportFeed".
 */
export interface TaskImportFeed {
  input: {
    feedSourceId: string;
    importRunId: string;
  };
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeliverLead".
 */
export interface TaskDeliverLead {
  input: {
    leadDeliveryId: string;
  };
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskJobsJanitor".
 */
export interface TaskJobsJanitor {
  input?: unknown;
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRecoverLeadDeliveries".
 */
export interface TaskRecoverLeadDeliveries {
  input?: unknown;
  output: {
    recovered: number;
    requeued: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCatalogLifecycle".
 */
export interface TaskCatalogLifecycle {
  input?: unknown;
  output: {
    expired: number;
    retained: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskLeadRetentionCleanup".
 */
export interface TaskLeadRetentionCleanup {
  input?: unknown;
  output: {
    anonymized: number;
    purged: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}